apiVersion: v1
kind: Template
metadata:
  name: hello-world-app
labels:
  template: "hello-world-app"

parameters:
- displayName: Name
  name: NAME
  required: true
  value: hello-world
- displayName: Port
  name: PORT
  required: true
  value: "8080"
- displayName: Git Address
  name: APP_GIT_ADDRESS
  required: true
  value: http://github.com/aramalipoor/hello-world.git

objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    replicas: 0
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
          - image: ${NAME}:latest
            imagePullPolicy: Always
            name: ${NAME}
            ports:
            - containerPort: ${PORT}
            terminationMessagePath: /dev/termination-log
        restartPolicy: Always
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: false
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    ports:
    - name: "${PORT}-tcp"
      port: "${PORT}"
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    host: ${NAME}.abar.cloud
    port:
      targetPort: "${PORT}-tcp"
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    to:
      kind: Service
      name: ${NAME}
      weight: 100
    wildcardPolicy: None

- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    name: ${NAME}
    labels:
      app: ${NAME}

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    postCommit:
      script: bundle exec rspec spec
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    runPolicy: Serial
    source:
      git:
        uri: ${APP_GIT_ADDRESS}
      type: Git
    strategy:
      type: Docker