apiVersion: v1
kind: Template
metadata:
  name: hello-world-pipeline
parameters:
- displayName: Name
  name: APP_NAME
  required: true
  value: hello-world
- name: GITHUB_WEBHOOK_SECRET
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
- name: GENERIC_WEBHOOK_SECRET
  displayName: Generic Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "${APP_NAME}", "kind": "DeploymentConfig"}]'
    labels:
      name: ${APP_NAME}-pipeline
    name: ${APP_NAME}-pipeline
  spec:
    source:
      git:
        uri: http://github.com/aramalipoor/hello_world.git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        env:
          - name: APP_NAME
            value: ${APP_NAME}
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
